### ISSUE TITLE
How i do provide API key?

### ISSUE THREAD

**Issue by schvabodka-man** [mayankchd/movie#3]
Hi, the app asks me to provide api key, but i really have no clue how to do that and there are no doc page about that

**Comment by Gelob** [comment]
Having this same issue.

**Comment by vandergast** [comment]
Same issue. "No API key provided"

**Comment by mayankchd** [comment]
Please send PR .

**Comment by schvabodka-man** [comment]
Pull request on what?

**Comment by mayankchd** [comment]
proving the API key

**Comment by brhx** [comment]
Hey guys, just to let you know as stated in #2, the API that `movie-cli` uses is no longer free, and thus the application no longer works.

Just as some constructive feedback, considering this is your application @mayankchd, providing more information about what sort of PR you want us to create or just any more information about the project status would be appreciated.

**Comment by agarrharr** [comment]
#6 Helps with this. Right now though, you would have to change the source code. It would be better if you could put your private APi key in a config file, like `~/.config/movie/config`.

The file could contain:

```
api_key = 8jasd98asdf
```

**Comment by rnmhdn** [comment]
you should update the readme so we would know that the app won't work before installing it...

**Comment by FutureQueenBee** [comment]
> #6 Helps with this. Right now though, you would have to change the source code. It would be better if you could put your private APi key in a config file, like `~/.config/movie/config`.
> 
> The file could contain:
> 
> ```
> api_key = 8jasd98asdf
> ```

Any possibility of a walk through on doing so? (changing API in source, I peeked, possibly not in the right place)

**Comment by brhx** [comment]
Sure!

1. Navigate to an empty directory on your computer to keep the source code and run the following command to download the source code for `movie`:

```bash
git clone https://https://github.com/mayankchd/movie.git
```

2. Enter the directory:

```bash
cd movie/
```

3. Find the `cli.js` file and then locate the section of code where `[yourkey]` exists:

https://github.com/mayankchd/movie/blob/c5366845686c1e2495f766ea6cbde6d0e4aad881/cli.js#L43

4. Then replace it with your API key. The string should look something like this (assuming your API key is `8jasd98asdf`):

```
'http://www.omdbapi.com/?apikey=8jasd98asdf&t='
```

5. Run the commands to install the dependencies and then to install the CLI to your computer:

```bash
npm install
npm link
```

> NOTE: if you get ERR! EACCES -13 or anything like that, make sure you put `sudo` before the command. This error can happen when you're not running the command as an administrator.

6. You should now be able to use the movie CLI 😄

**Comment by mayankchd** [comment]
@FutureQueenBee @sam3d Have fixed this. Added a default key.. Need to make key configurable from CLI though.
<img width="1440" alt="Screenshot 2019-06-24 at 1 54 35 AM" src="https://user-images.githubusercontent.com/5843024/59981583-0f866b00-9623-11e9-8258-db7234277a17.png">
